# Web debug toolbar
_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix: /_wdt
_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix: /_profiler

# Fork routes
_main:
    resource: routing.yml
